import mongoose from "mongoose";

const invoiceSchema = new mongoose.Schema({
  pname: {type: String, required: true},
  GSTN: {type: String, required: true},
  add1: {type: String},
  add2: {type: String},
  add3: {type: String},
  type: {type: String},
  no: {type: String},
  invNo: {type: String},
  IDate: {type: Date},
  d: {type: Number},
  m: {type: Number},
  y: {type: Number},
  ChNo: {type: String},
  CDate: {type: Date},
  PONo: {type: String},
  Pdate: {type: Date},
  Eway: {type: String},

  sr1: {type: Number},
  part1: {type: String},
  HSN1: {type: Number},
  QTY1: {type: Number},
  typ1: {type: String},
  rate1: {type: Number},
  amt1: {type: Number},
  amtF1: {type: String},

  sr2: {type: Number},
  part2: {type: String},
  HSN2: {type: Number},
  QTY2: {type: Number},
  typ2: {type: String},
  rate2: {type: Number},
  amt2: {type: Number},
  amtF2: {type: String},

  sr3: {type: Number},
  part3: {type: String},
  HSN3: {type: Number},
  QTY3: {type: Number},
  typ3: {type: String},
  rate3: {type: Number},
  amt3: {type: Number},
  amtF3: {type: String},

  sr4: {type: Number},
  part4: {type: String},
  HSN4: {type: Number},
  QTY4: {type: Number},
  typ4: {type: String},
  rate4: {type: Number},
  amt4: {type: Number},
  amtF4: {type: String},

  sr5: {type: Number},
  part5: {type: String},
  HSN5: {type: Number},
  QTY5: {type: Number},
  typ5: {type: String},
  rate5: {type: Number},
  amt5: {type: Number},
  amtF5: {type: String},

  sr6: {type: Number},
  part6: {type: String},
  HSN6: {type: Number},
  QTY6: {type: Number},
  typ6: {type: String},
  rate6: {type: Number},
  amt6: {type: Number},
  amtF6: {type: String},

  sr7: {type: Number},
  part7: {type: String},
  HSN7: {type: Number},
  QTY7: {type: Number},
  typ7: {type: String},
  rate7: {type: Number},
  amt7: {type: Number},
  amtF7: {type: String},

  sr8: {type: Number},
  part8: {type: String},
  HSN8: {type: Number},
  QTY8: {type: Number},
  typ8: {type: String},
  rate8: {type: Number},
  amt8: {type: Number},
  amtF8: {type: String},

  sr9: {type: Number},
  part9: {type: String},
  HSN9: {type: Number},
  QTY9: {type: Number},
  typ9: {type: String},
  rate9: {type: Number},
  amt9: {type: Number},
  amtF9: {type: String},

  sr10: {type: Number},
  part10: {type: String},
  HSN10: {type: Number},
  QTY10: {type: Number},
  typ10: {type: String},
  rate10: {type: Number},
  amt10: {type: Number},
  amtF10: {type: String},

  sr11: {type: Number},
  part11: {type: String},
  HSN11: {type: Number},
  QTY11: {type: Number},
  typ11: {type: String},
  rate11: {type: Number},
  amt11: {type: Number},
  amtF11: {type: String},

  sr12: {type: Number},
  part12: {type: String},
  HSN12: {type: Number},
  QTY12: {type: Number},
  typ12: {type: String},
  rate12: {type: Number},
  amt12: {type: Number},
  amtF12: {type: String},

  sr13: {type: Number},
  part13: {type: String},
  HSN13: {type: Number},
  QTY13: {type: Number},
  typ13: {type: String},
  rate13: {type: Number},
  amt13: {type: Number},
  amtF13: {type: String},

  discount: {type: Number, required: true, default: 0},
  discamt: {type: Number, required: true, default: 0},
  pnf: {type: Number, required: true, default: 0},
  total: {type: Number, required: true, default: 0},
  lessdisc: {type: Number, required: true, default: 0},
  CGST: {type: Number, required: true, default: 0},
  SGST: {type: Number, required: true, default: 0},
  IGST: {type: Number, required: true, default: 0},
  Gtotal: {type: Number, required: true, default: 0},
});

module.exports = mongoose.model("Invoice", invoiceSchema);
